# Generated by Django 4.0.2 on 2022-02-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerId', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('firstName', models.CharField(max_length=500)),
                ('lastName', models.CharField(blank=True, max_length=500)),
                ('dateOfBirth', models.DateField()),
                ('currencyBalance', models.FloatField()),
                ('pageVisitors', models.IntegerField(blank=True)),
            ],
        ),
    ]
