# Generated by Django 4.0.2 on 2022-02-10 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='currencyBalance',
            new_name='currency_balance',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customerId',
            new_name='customer_id',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='dateOfBirth',
            new_name='date_of_birth',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='lastName',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='pageVisitors',
            new_name='page_visitors',
        ),
    ]
