# Generated by Django 4.0.2 on 2022-02-10 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('advertisement_title', models.CharField(default='Advertisement title', max_length=100)),
                ('advertisement_description', models.CharField(default='Advertisement description', max_length=500)),
                ('how_to_donate', models.CharField(default='How to donate', max_length=500)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('background_color', models.CharField(blank=True, max_length=100)),
                ('learn_more_link', models.URLField(blank=True)),
            ],
        ),
    ]
