# Generated by Django 4.0.2 on 2022-02-14 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerOrder', '0002_rename_itemcount_customerorder_item_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='order_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
