# Generated by Django 4.0.2 on 2022-02-14 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerOrder', '0005_rename_order_id_customerorder_orders_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerorder',
            old_name='orders_id',
            new_name='order_id',
        ),
    ]
